# SuperDARN Performance Testing Environment
version: '3.8'

services:
  # Interactive testing environment
  superdarn-dev:
    build:
      context: .
      dockerfile: dockerfile.fitacf
    container_name: superdarn-dev
    volumes:
      - ./codebase:/workspace/codebase
      - ./scripts:/workspace/scripts
      - ./test-results:/workspace/results
    environment:
      - OMP_NUM_THREADS=4
      - OMP_SCHEDULE=dynamic,1
      - OMP_PROC_BIND=true
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash

  # Automated performance testing
  superdarn-test:
    build:
      context: .
      dockerfile: dockerfile.fitacf
    container_name: superdarn-test
    volumes:
      - ./codebase:/workspace/codebase
      - ./scripts:/workspace/scripts  
      - ./test-results:/workspace/results
    environment:
      - OMP_NUM_THREADS=8
    working_dir: /workspace
    command: >
      /bin/bash -c "
        echo '🚀 Starting SuperDARN Performance Tests...'
        
        # Build FitACF tests
        cd codebase/superdarn/src.lib/tk/fitacf_v3.0/src
        make -f makefile_standalone clean
        make -f makefile_standalone tests
        
        echo '📊 Running FitACF Array vs LinkedList comparison...'
        for threads in 1 2 4 8; do
          echo \"Testing with \$threads threads...\"
          OMP_NUM_THREADS=\$threads ./test_array_vs_llist | tee /workspace/results/fitacf_\$threads.txt
        done
        
        # Build and test fit_speck_removal
        cd /workspace/codebase/superdarn/src.bin/tk/tool/fit_speck_removal.1.0
        echo '🔧 Testing fit_speck_removal optimizations...'
        
        # Generate test data
        cd /workspace
        ./scripts/generate_test_fitacf_data.sh medium
        
        # Test different optimization levels
        for opt in O2 O3 Ofast; do
          echo \"Testing optimization: \$opt\"
          cd /workspace/codebase/superdarn/src.bin/tk/tool/fit_speck_removal.1.0
          
          cp makefile makefile.backup
          sed -i \"s/-O2/-\$opt/g\" makefile
          make clean && make
          
          echo \"Running performance test with -\$opt...\"
          time ./fit_speck_removal /workspace/test_data_medium.fitacf > /workspace/results/speck_\$opt.fitacf 2>&1 | tee /workspace/results/timing_\$opt.txt
          
          mv makefile.backup makefile
        done
        
        echo '✅ All tests completed! Results in /workspace/results/'
      "
