apiVersion: v1
kind: Service
metadata:
  name: {{ include "superdarn.fullname" . }}-frontend
  labels:
    {{- include "superdarn.labels" . | nindent 4 }}
    {{- include "superdarn.frontendSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "superdarn.frontendSelectorLabels" . | nindent 4 }}
