apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "superdarn.fullname" . }}-uploads
  labels:
    {{- include "superdarn.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "superdarn.fullname" . }}-results
  labels:
    {{- include "superdarn.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.results.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.results.size }}
