apiVersion: v1
kind: Service
metadata:
  name: {{ include "superdarn-workbench.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superdarn-workbench.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "superdarn-workbench.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
