name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.

jobs:
    build:

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2


            - name: Build and push Docker RSTDocker
              uses: docker/build-push-action@v2
              with:
                context: . # Path to the Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                #tags are both for pushing and for later builds to reference, first is the name of the image, second is the tag of the image
                tags: ${{ secrets.DOCKER_USERNAME }}/superdarn_rstbase:latest 


